# Generated by Django 4.2.1 on 2023-06-30 22:03

import apps.profiles.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Business Address')),
                ('phone_number', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('org_id', models.CharField(default=apps.profiles.utils.generate_unique_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('industry', models.CharField(choices=[('AGENCY', 'AGENCY'), ('AGRICULTURE', 'AGRICULTURE'), ('ART AND DESIGN', 'ART'), ('CONSTRUCTION', 'AUTOMOTIVE'), ('CONSULTING', 'CONSULTING'), ('EDUCATION', 'EDUCATION')], max_length=100)),
                ('business', models.CharField(choices=[('FREELANCING', 'FREELANCING'), ('NGO', 'NGO'), ('PROFIT BUSINESS', 'PROFIT_BUSINESS')], max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('base_currency', models.CharField(blank=True, choices=[('FREELANCING', 'FREELANCING'), ('NGO', 'NGO'), ('PROFIT BUSINESS', 'PROFIT_BUSINESS')], max_length=30)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
