# Generated by Django 4.2.1 on 2023-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kyc_submitted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='on_boarding_complete_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_security_number',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='saascrafters', max_length=100, verbose_name='Name of Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Bello ABdulHakeem', max_length=125, verbose_name='FullName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Lagos', max_length=70, verbose_name='Select State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
