# Generated by Django 4.2.1 on 2023-06-30 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('W', 'Weekly'), ('BW', 'Bi-Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('HY', 'Half a Year'), ('Y', 'Yearly')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 22, 3, 33, 343203, tzinfo=datetime.timezone.utc), verbose_name='Due Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('Once', 'Once'), ('Recurring', 'Recurring')], default='ONCE', max_length=20, verbose_name='Invoice Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='recurring',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
